# socmod examples

Examples demonstrating how to use the [socmod](https://css4s.github.io/socmod) library for modeling social behavior. The library could possibly be used for computational modeling in other fields like ecology and perhaps biology more broadly.

## Index

-   [**Football/soccer example**](football-R6-example/index.qmd) that illustrates how to use the [R6 library](https://github.com/r-lib/R6) for object-oriented programming. Understanding object-oriented programming concepts will help design agent-based models of social behavior, and is a key component in the design of `socmod`.

- [**Diffusion in _minority-majority_ populations**](turner-etal-2023-philtransb/index.qmd) where simulated adaptation prevalence can be boosted by harnessing prominent minority groups and cohesive majorities [@Turner2023]

#### Planned

-   Simple diffusion of adaptive behaviors with different learning strategies

-   Medici solar panel business opportunity

-   A simplified version of Turner et al 2023
